// GENERATED by scripts/gen_module_prelude.py — 请勿手改，手改会被覆盖。
//
// 不变量：一切非本模块头（标准库/系统/第三方/其它 galay 模块）必须在全局
// 模块片段内展开；purview 只允许本模块头。本文件由工具从各 .cppm 的 include
// 集自动推导，条目为安全超集（__has_include 守卫，平台缺失自动跳过）。
// 增删 include 后请重新生成：
//
//     scripts/gen_module_prelude.py            # 全部模块
//     scripts/gen_module_prelude.py --check    # 门禁校验（漂移则失败）
//
// 依据：docs/plans/module-support.md「模块接口单元结构」。

#pragma once

#if __has_include("../../galay-etcd/base/etcd_config.h")
#include "../../galay-etcd/base/etcd_config.h"
#endif
#if __has_include("../../galay-etcd/base/etcd_error.h")
#include "../../galay-etcd/base/etcd_error.h"
#endif
#if __has_include("../../galay-etcd/base/etcd_types.h")
#include "../../galay-etcd/base/etcd_types.h"
#endif
#if __has_include("../../galay-etcd/base/etcd_value.h")
#include "../../galay-etcd/base/etcd_value.h"
#endif
#if __has_include("../../galay-etcd/base/network_cfg.h")
#include "../../galay-etcd/base/network_cfg.h"
#endif
#if __has_include("../../galay-etcd/sync/etcd_client.h")
#include "../../galay-etcd/sync/etcd_client.h"
#endif
#if __has_include("../../galay-kernel/async/async_mutex.h")
#include "../../galay-kernel/async/async_mutex.h"
#endif
#if __has_include("../../galay-kernel/async/async_tcp.h")
#include "../../galay-kernel/async/async_tcp.h"
#endif
#if __has_include("../../galay-kernel/async/async_waiter.h")
#include "../../galay-kernel/async/async_waiter.h"
#endif
#if __has_include("../../galay-kernel/common/balancer.hpp")
#include "../../galay-kernel/common/balancer.hpp"
#endif
#if __has_include("../../galay-kernel/common/concepts.h")
#include "../../galay-kernel/common/concepts.h"
#endif
#if __has_include("../../galay-kernel/common/defn.hpp")
#include "../../galay-kernel/common/defn.hpp"
#endif
#if __has_include("../../galay-kernel/common/error.h")
#include "../../galay-kernel/common/error.h"
#endif
#if __has_include("../../galay-kernel/common/handle_option.h")
#include "../../galay-kernel/common/handle_option.h"
#endif
#if __has_include("../../galay-kernel/common/host.hpp")
#include "../../galay-kernel/common/host.hpp"
#endif
#if __has_include("../../galay-kernel/common/kernel_config.h")
#include "../../galay-kernel/common/kernel_config.h"
#endif
#if __has_include("../../galay-kernel/common/log_macro.h")
#include "../../galay-kernel/common/log_macro.h"
#endif
#if __has_include("../../galay-kernel/common/logger.h")
#include "../../galay-kernel/common/logger.h"
#endif
#if __has_include("../../galay-kernel/common/sleep.hpp")
#include "../../galay-kernel/common/sleep.hpp"
#endif
#if __has_include("../../galay-kernel/common/timer.hpp")
#include "../../galay-kernel/common/timer.hpp"
#endif
#if __has_include("../../galay-kernel/common/timer_manager.hpp")
#include "../../galay-kernel/common/timer_manager.hpp"
#endif
#if __has_include("../../galay-kernel/common/timer_manager_mt.hpp")
#include "../../galay-kernel/common/timer_manager_mt.hpp"
#endif
#if __has_include("../../galay-kernel/concurrency/mpsc/unbounded_channel.h")
#include "../../galay-kernel/concurrency/mpsc/unbounded_channel.h"
#endif
#if __has_include("../../galay-kernel/core/awaitable.h")
#include "../../galay-kernel/core/awaitable.h"
#endif
#if __has_include("../../galay-kernel/core/awaitable.inl")
#include "../../galay-kernel/core/awaitable.inl"
#endif
#if __has_include("../../galay-kernel/core/blocking_executor.h")
#include "../../galay-kernel/core/blocking_executor.h"
#endif
#if __has_include("../../galay-kernel/core/io_controller.hpp")
#include "../../galay-kernel/core/io_controller.hpp"
#endif
#if __has_include("../../galay-kernel/core/io_handlers.hpp")
#include "../../galay-kernel/core/io_handlers.hpp"
#endif
#if __has_include("../../galay-kernel/core/io_scheduler.hpp")
#include "../../galay-kernel/core/io_scheduler.hpp"
#endif
#if __has_include("../../galay-kernel/core/runtime.h")
#include "../../galay-kernel/core/runtime.h"
#endif
#if __has_include("../../galay-kernel/core/scheduler.hpp")
#include "../../galay-kernel/core/scheduler.hpp"
#endif
#if __has_include("../../galay-kernel/core/task.h")
#include "../../galay-kernel/core/task.h"
#endif
#if __has_include("../../galay-kernel/core/timeout.hpp")
#include "../../galay-kernel/core/timeout.hpp"
#endif
#if __has_include("../../galay-kernel/core/timer_scheduler.h")
#include "../../galay-kernel/core/timer_scheduler.h"
#endif
#if __has_include("../../galay-kernel/core/wait_registration.h")
#include "../../galay-kernel/core/wait_registration.h"
#endif
#if __has_include("../../galay-kernel/core/waker.h")
#include "../../galay-kernel/core/waker.h"
#endif
#if __has_include("../../galay-kernel/core/watch_defs.hpp")
#include "../../galay-kernel/core/watch_defs.hpp"
#endif
#if __has_include("../../galay-kernel/parallel/parallel_scheduler.h")
#include "../../galay-kernel/parallel/parallel_scheduler.h"
#endif
#if __has_include("../../galay-utils/cache/ring_buffer.hpp")
#include "../../galay-utils/cache/ring_buffer.hpp"
#endif
#if __has_include("../../galay-utils/common/defn.hpp")
#include "../../galay-utils/common/defn.hpp"
#endif
#if __has_include("../../galay-utils/common/macro.hpp")
#include "../../galay-utils/common/macro.hpp"
#endif
#if __has_include("../../galay-utils/tool/circuit_breaker.hpp")
#include "../../galay-utils/tool/circuit_breaker.hpp"
#endif
#if __has_include("../../galay-utils/tool/rate_limiter.hpp")
#include "../../galay-utils/tool/rate_limiter.hpp"
#endif
#if __has_include(<WinSock2.h>)
#include <WinSock2.h>
#endif
#if __has_include(<algorithm>)
#include <algorithm>
#endif
#if __has_include(<arpa/inet.h>)
#include <arpa/inet.h>
#endif
#if __has_include(<array>)
#include <array>
#endif
#if __has_include(<atomic>)
#include <atomic>
#endif
#if __has_include(<bit>)
#include <bit>
#endif
#if __has_include(<cctype>)
#include <cctype>
#endif
#if __has_include(<cerrno>)
#include <cerrno>
#endif
#if __has_include(<charconv>)
#include <charconv>
#endif
#if __has_include(<chrono>)
#include <chrono>
#endif
#if __has_include(<concepts>)
#include <concepts>
#endif
#if __has_include(<condition_variable>)
#include <condition_variable>
#endif
#if __has_include(<coroutine>)
#include <coroutine>
#endif
#if __has_include(<cstddef>)
#include <cstddef>
#endif
#if __has_include(<cstdint>)
#include <cstdint>
#endif
#if __has_include(<cstdio>)
#include <cstdio>
#endif
#if __has_include(<cstdlib>)
#include <cstdlib>
#endif
#if __has_include(<cstring>)
#include <cstring>
#endif
#if __has_include(<ctime>)
#include <ctime>
#endif
#if __has_include(<deque>)
#include <deque>
#endif
// GCC 的 x86 intrinsic 头从 <emmintrin.h> 引入 <mm_malloc.h>，其 TU-local 辅助函数一旦在 purview 内展开，GCC 报 "exporting declaration ... with internal linkage"。
#if (defined(__x86_64__) || defined(__i386__)) && __has_include(<emmintrin.h>)
#include <emmintrin.h>
#endif
#if __has_include(<expected>)
#include <expected>
#endif
#if __has_include(<fcntl.h>)
#include <fcntl.h>
#endif
#if __has_include(<filesystem>)
#include <filesystem>
#endif
#if __has_include(<format>)
#include <format>
#endif
// 标准库类若在 purview 内首次展开，会被挂到命名模块上（"conflicting declaration of 'class std::basic_filebuf' in module ..."）。
#if __has_include(<fstream>)
#include <fstream>
#endif
#if __has_include(<functional>)
#include <functional>
#endif
#if __has_include(<galay/thirdparty/concurrentqueue/moodycamel/blockingconcurrentqueue.h>)
#include <galay/thirdparty/concurrentqueue/moodycamel/blockingconcurrentqueue.h>
#endif
#if __has_include(<galay/thirdparty/concurrentqueue/moodycamel/concurrentqueue.h>)
#include <galay/thirdparty/concurrentqueue/moodycamel/concurrentqueue.h>
#endif
#if defined(_MSC_VER) && __has_include(<intrin.h>)
#include <intrin.h>
#endif
// <libaio.h> 的 io_* 帮助函数是 static inline：在 purview 内展开同样触发 "exporting declaration ... with internal linkage"。
#if __has_include(<libaio.h>)
#include <libaio.h>
#endif
// liburing 通过 Linux 头文件暴露通用的 BLOCK_SIZE 宏；清理该宏以免与 vendored concurrentqueue 的同名类成员冲突。
#if __has_include(<liburing.h>)
#include <liburing.h>
#endif
#ifdef BLOCK_SIZE
#undef BLOCK_SIZE
#endif
#if __has_include(<limits>)
#include <limits>
#endif
#if __has_include(<linux/time_types.h>)
#include <linux/time_types.h>
#endif
#if __has_include(<list>)
#include <list>
#endif
#if __has_include(<memory>)
#include <memory>
#endif
#if __has_include(<mutex>)
#include <mutex>
#endif
#if __has_include(<netinet/in.h>)
#include <netinet/in.h>
#endif
#if __has_include(<new>)
#include <new>
#endif
#if __has_include(<optional>)
#include <optional>
#endif
#if __has_include(<pthread.h>)
#include <pthread.h>
#endif
#if __has_include(<random>)
#include <random>
#endif
#if __has_include(<sched.h>)
#include <sched.h>
#endif
#if __has_include(<span>)
#include <span>
#endif
#if __has_include(<sstream>)
#include <sstream>
#endif
#if __has_include(<string>)
#include <string>
#endif
#if __has_include(<string_view>)
#include <string_view>
#endif
#if __has_include(<sys/epoll.h>)
#include <sys/epoll.h>
#endif
#if __has_include(<sys/event.h>)
#include <sys/event.h>
#endif
#if __has_include(<sys/inotify.h>)
#include <sys/inotify.h>
#endif
#if __has_include(<sys/mman.h>)
#include <sys/mman.h>
#endif
#if __has_include(<sys/sendfile.h>)
#include <sys/sendfile.h>
#endif
#if __has_include(<sys/socket.h>)
#include <sys/socket.h>
#endif
#if __has_include(<sys/stat.h>)
#include <sys/stat.h>
#endif
#if __has_include(<sys/syscall.h>)
#include <sys/syscall.h>
#endif
#if __has_include(<sys/types.h>)
#include <sys/types.h>
#endif
#if __has_include(<sys/uio.h>)
#include <sys/uio.h>
#endif
#if __has_include(<thread>)
#include <thread>
#endif
#if __has_include(<type_traits>)
#include <type_traits>
#endif
#if __has_include(<unistd.h>)
#include <unistd.h>
#endif
#if __has_include(<unordered_map>)
#include <unordered_map>
#endif
#if __has_include(<unordered_set>)
#include <unordered_set>
#endif
#if __has_include(<utility>)
#include <utility>
#endif
#if __has_include(<variant>)
#include <variant>
#endif
#if __has_include(<vector>)
#include <vector>
#endif
