set(work "${GALAY_BINARY_DIR}/api-embedded-generator")
set(assets "${work}/assets")
file(MAKE_DIRECTORY "${work}")
file(COPY "${GALAY_SOURCE_DIR}/assets/swagger-ui/" DESTINATION "${assets}")

function(generate name expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DASSET_DIR=${assets}"
        "-DOUTPUT_FILE=${work}/${name}.cc" -P "${GALAY_SOURCE_DIR}/cmake/EmbedSwaggerUi.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${work}/${name}.log" "${output}\n${error}")
    if(expected_error STREQUAL "")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name}: generation failed: ${output}\n${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected_error}")
        message(FATAL_ERROR "${name}: expected ${expected_error}, got ${result}: ${output}\n${error}")
    elseif(EXISTS "${work}/${name}.cc")
        message(FATAL_ERROR "${name}: failed verification wrote a generated translation unit")
    endif()
endfunction()

generate(valid "")
generate(deterministic "")
file(SHA256 "${work}/valid.cc" first)
file(SHA256 "${work}/deterministic.cc" second)
if(NOT first STREQUAL second)
    message(FATAL_ERROR "Swagger UI generation is not deterministic")
endif()

file(APPEND "${assets}/swagger-ui.css" "corrupted upstream bytes")
generate(corrupt "Swagger UI SHA256 mismatch for swagger-ui.css")
file(COPY "${GALAY_SOURCE_DIR}/assets/swagger-ui/swagger-ui.css" DESTINATION "${assets}")
file(REMOVE "${assets}/favicon-16x16.png")
generate(missing "Swagger UI resource missing")
file(COPY "${GALAY_SOURCE_DIR}/assets/swagger-ui/favicon-16x16.png" DESTINATION "${assets}")
file(WRITE "${assets}/NOTICE" "")
generate(empty "Swagger UI resource must be nonempty")
file(COPY "${GALAY_SOURCE_DIR}/assets/swagger-ui/NOTICE" DESTINATION "${assets}")

file(READ "${assets}/SHA256SUMS" manifest)
file(WRITE "${assets}/SHA256SUMS" "../invalid-manifest\n")
generate(invalid_manifest "SHA256SUMS must contain exactly seven")
file(STRINGS "${GALAY_SOURCE_DIR}/assets/swagger-ui/SHA256SUMS" lines)
list(GET lines 0 duplicate)
string(REGEX REPLACE "[0-9a-f]+  NOTICE" "${duplicate}" duplicated "${manifest}")
file(WRITE "${assets}/SHA256SUMS" "${duplicated}")
generate(duplicate "Invalid or duplicate Swagger UI SHA256SUMS entry")
file(WRITE "${assets}/SHA256SUMS" "${manifest}")

file(APPEND "${assets}/README.md" "\nFixture metadata change.\n")
generate(updated "")
file(SHA256 "${work}/updated.cc" changed)
if(changed STREQUAL first)
    message(FATAL_ERROR "Updated provenance did not reach generated resources")
endif()
message(STATUS "Embedded generator: deterministic, exact manifest, corruption/missing/empty rejected, metadata updated")
