// GENERATED by scripts/gen_module_prelude.py — 请勿手改，手改会被覆盖。
//
// 不变量：一切非本模块头（标准库/系统/第三方/其它 galay 模块）必须在全局
// 模块片段内展开；purview 只允许本模块头。本文件由工具从各 .cppm 的 include
// 集自动推导，条目为安全超集（__has_include 守卫，平台缺失自动跳过）。
// 增删 include 后请重新生成：
//
//     scripts/gen_module_prelude.py            # 全部模块
//     scripts/gen_module_prelude.py --check    # 门禁校验（漂移则失败）
//
// 依据：docs/plans/module-support.md「模块接口单元结构」。

#pragma once

#if __has_include("../../galay-kernel/common/log_macro.h")
#include "../../galay-kernel/common/log_macro.h"
#endif
#if __has_include("../../galay-kernel/common/logger.h")
#include "../../galay-kernel/common/logger.h"
#endif
#if __has_include(<array>)
#include <array>
#endif
#if __has_include(<atomic>)
#include <atomic>
#endif
#if __has_include(<chrono>)
#include <chrono>
#endif
#if __has_include(<concepts>)
#include <concepts>
#endif
#if __has_include(<cstddef>)
#include <cstddef>
#endif
#if __has_include(<cstdint>)
#include <cstdint>
#endif
#if __has_include(<expected>)
#include <expected>
#endif
#if __has_include(<filesystem>)
#include <filesystem>
#endif
#if __has_include(<format>)
#include <format>
#endif
// 标准库类若在 purview 内首次展开，会被挂到命名模块上（"conflicting declaration of 'class std::basic_filebuf' in module ..."）。
#if __has_include(<fstream>)
#include <fstream>
#endif
#if __has_include(<functional>)
#include <functional>
#endif
#if __has_include(<iosfwd>)
#include <iosfwd>
#endif
#if __has_include(<memory>)
#include <memory>
#endif
#if __has_include(<mutex>)
#include <mutex>
#endif
#if __has_include(<optional>)
#include <optional>
#endif
#if __has_include(<source_location>)
#include <source_location>
#endif
#if __has_include(<span>)
#include <span>
#endif
#if __has_include(<string>)
#include <string>
#endif
#if __has_include(<string_view>)
#include <string_view>
#endif
#if __has_include(<thread>)
#include <thread>
#endif
#if __has_include(<utility>)
#include <utility>
#endif
#if __has_include(<variant>)
#include <variant>
#endif
#if __has_include(<vector>)
#include <vector>
#endif
