#!/usr/bin/env python3
"""Generate (or verify) module_prelude.hpp for every galay C++ module.

 galay 的每个 C++ 模块都带一个过渡性模块接口 module/galay_*.cppm：

     module;
     #include "module_prelude.hpp"                // 全局模块片段
     export module galay.<name>;
     export extern "C++" { #include "../..." }    // purview：本模块头文件

 唯一需要维持的结构不变量（docs/plans/module-support.md「模块接口单元结构」）：

     一切非本模块的头 —— 标准库、系统、第三方、其它 galay 模块 —— 必须在
     全局模块片段内展开；purview 只允许本模块头。

 某个非本模块头若第一次展开发生在 purview 内，其声明会被挂到命名模块上
 （libstdc++ 的 <fstream> → "conflicting declaration ... in module
 'galay.rpc'"），其中 TU-local 实体（<libaio.h>/<emmintrin.h> 的 static
 inline）更是直接 "exporting declaration ... with internal linkage" 硬错误。

 本工具把该不变量机械化：解析每个 .cppm 的 include 集（全局片段 + purview
 一起作为根），递归展开本模块头，收集所有可达的非本模块头并重写
 module_prelude.hpp（全部用 __has_include 守卫，平台缺失时自动跳过，因此
 超集是安全的 no-op —— 宁多勿漏）。手写清单已多次漂移（galay-rpc 缺
 <fstream>、galay-mcp 缺 <emmintrin.h>），此工具使之不再依赖记忆。

     scripts/gen_module_prelude.py                # 重写全部 prelude
     scripts/gen_module_prelude.py --check        # 校验；漂移则 diff + 退出码 1
     scripts/gen_module_prelude.py --module galay-rpc

 --check 供门禁使用（CTest/CI）：任何新 include 未进入 prelude 即失败。
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_CPP = REPO_ROOT / "src" / "cpp"

INCLUDE_ANGLE = re.compile(r'#\s*include\s*<([^>\n]+)>')
INCLUDE_QUOTED = re.compile(r'#\s*include\s*"([^"\n]+)"')
LINE_COMMENT = re.compile(r'//[^\n]*')
BLOCK_COMMENT = re.compile(r'/\*.*?\*/', re.S)
EXPORT_MODULE = re.compile(r'^\s*export\s+module\s+', re.M)

# 个别头需要解释"为什么必须待在全局片段"，生成时原样写入 prelude。
ANNOTATIONS: dict[str, str] = {
    "<emmintrin.h>":
        "GCC 的 x86 intrinsic 头从 <emmintrin.h> 引入 <mm_malloc.h>，其 TU-local "
        "辅助函数一旦在 purview 内展开，GCC 报 \"exporting declaration ... with "
        "internal linkage\"。",
    "<libaio.h>":
        "<libaio.h> 的 io_* 帮助函数是 static inline：在 purview 内展开同样触发 "
        "\"exporting declaration ... with internal linkage\"。",
    "<fstream>":
        "标准库类若在 purview 内首次展开，会被挂到命名模块上（\"conflicting "
        "declaration of 'class std::basic_filebuf' in module ...\"）。",
    "<liburing.h>":
        "liburing 通过 Linux 头文件暴露通用的 BLOCK_SIZE 宏；清理该宏以免与 "
        "vendored concurrentqueue 的同名类成员冲突。",
}

# Some platform headers expose short, generic macros that are not part of their
# useful C++ interface.  Keep the cleanup next to the generated include so it
# also applies when a header is pulled in only because another platform branch
# was scanned by this tool.
POST_INCLUDE_CLEANUPS: dict[str, tuple[str, ...]] = {
    "<liburing.h>": ("#ifdef BLOCK_SIZE", "#undef BLOCK_SIZE", "#endif"),
}

HEADER_COMMENT = """\
// GENERATED by scripts/gen_module_prelude.py — 请勿手改，手改会被覆盖。
//
// 不变量：一切非本模块头（标准库/系统/第三方/其它 galay 模块）必须在全局
// 模块片段内展开；purview 只允许本模块头。本文件由工具从各 .cppm 的 include
// 集自动推导，条目为安全超集（__has_include 守卫，平台缺失自动跳过）。
// 增删 include 后请重新生成：
//
//     scripts/gen_module_prelude.py            # 全部模块
//     scripts/gen_module_prelude.py --check    # 门禁校验（漂移则失败）
//
// 依据：docs/plans/module-support.md「模块接口单元结构」。
"""


def strip_comments(text: str) -> str:
    return BLOCK_COMMENT.sub("", LINE_COMMENT.sub("", text))


def include_matches(text: str):
    """所有 include 匹配，形如 (spelling, group1, offset)。"""
    for m in INCLUDE_ANGLE.finditer(text):
        yield f"<{m.group(1)}>", m.group(1), m.start()
    for m in INCLUDE_QUOTED.finditer(text):
        yield f'"{m.group(1)}"', m.group(1), m.start()


class Module:
    """一个 galay C++ 模块的 prelude 需求推导。"""

    def __init__(self, src_dir: Path) -> None:
        self.src_dir = src_dir                        # .../src/cpp/<module>
        self.name = src_dir.name
        self.module_dir = src_dir / "module"
        self.cppm_files = sorted(self.module_dir.glob("*.cppm"))
        self.external: set[str] = set()               # '<h>' 与 '"rel"' 两种拼写
        self.purview_foreign: set[str] = set()        # purview 里直接出现的非本模块头
        self._seen: set[Path] = set()

    def collect(self) -> None:
        for cppm in self.cppm_files:
            text = strip_comments(cppm.read_text(encoding="utf-8", errors="replace"))
            marker = EXPORT_MODULE.search(text)
            if marker is None:
                raise SystemExit(f"{cppm}: 未找到 'export module' 行")
            for spelling, header, offset in include_matches(text):
                in_purview = offset > marker.start()
                if spelling.startswith("<"):
                    self.external.add(spelling)
                    if in_purview:
                        self.purview_foreign.add(spelling)
                    continue
                target = (cppm.parent / header).resolve()
                if not target.is_file():
                    continue                          # __has_include 守卫的可选头
                if self._is_own(target):
                    self._walk(target)                # 本模块头：递归展开其依赖
                else:
                    self.external.add(self._spelling(target, cppm.parent, header))
                    self._walk(target)
                    if in_purview:
                        self.purview_foreign.add(self._spelling(target, cppm.parent, header))

    def _walk(self, header: Path) -> None:
        # The prelude is generated output, not a source dependency.  Walking
        # it would make stale entries self-preserving across regenerations.
        if header == (self.module_dir / "module_prelude.hpp").resolve():
            return
        if header in self._seen:
            return
        self._seen.add(header)
        text = strip_comments(header.read_text(encoding="utf-8", errors="replace"))
        for spelling, inc, _ in include_matches(text):
            if spelling.startswith("<"):
                self.external.add(spelling)
                continue
            target = (header.parent / inc).resolve()
            if not target.is_file():
                continue
            if self._is_own(target):
                self._walk(target)
            else:
                self.external.add(self._spelling(target, header.parent, inc))
                self._walk(target)                    # 外部头的传递依赖同样收进来

    def _is_own(self, path: Path) -> bool:
        try:
            path.relative_to(self.src_dir)
            return True
        except ValueError:
            return False

    def _spelling(self, target: Path, includer_dir: Path, original: str) -> str:
        """prelude 中使用的 include 拼写。

        其它 galay 模块的头统一相对本模块 module/ 目录拼写（源码树与安装树
        深度一致，两种布局均可解析）；其余外部头保留原拼写（经 -I 解析）。
        """
        try:
            target.relative_to(SRC_CPP)
        except ValueError:
            return f'"{original}"'
        return f'"{os.path.relpath(target, self.module_dir)}"'


def render(module: Module) -> str:
    lines = [HEADER_COMMENT, "#pragma once", ""]
    for spelling in sorted(module.external):
        if spelling in ANNOTATIONS:
            lines.append(f"// {ANNOTATIONS[spelling]}")
        lines.append(f"#if __has_include({spelling})")
        lines.append(f"#include {spelling}")
        lines.append("#endif")
        for cleanup in POST_INCLUDE_CLEANUPS.get(spelling, ()):
            lines.append(cleanup)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="只校验不重写；有漂移则打印 diff 并退出 1")
    parser.add_argument("--module", action="append", default=[],
                        help="只处理指定模块（可多次；默认全部）")
    args = parser.parse_args()

    modules = sorted(p for p in SRC_CPP.iterdir() if p.is_dir())
    if args.module:
        wanted = set(args.module)
        modules = [m for m in modules if m.name in wanted]
        unknown = wanted - {m.name for m in modules}
        if unknown:
            parser.error(f"未知模块: {', '.join(sorted(unknown))}")

    drifted: list[str] = []
    for src_dir in modules:
        module = Module(src_dir)
        if not module.cppm_files:
            continue                                  # 无模块接口的目录
        module.collect()
        target = module.module_dir / "module_prelude.hpp"
        rendered = render(module)
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        rel = target.relative_to(REPO_ROOT)
        if current == rendered:
            print(f"ok       {rel} ({len(module.external)} headers)")
        elif args.check:
            drifted.append(str(rel))
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(keepends=True), rendered.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)", tofile=f"{rel} (expected)"))
        else:
            target.write_text(rendered, encoding="utf-8")
            print(f"rewrote  {rel} ({len(module.external)} headers)")

        for spelling in sorted(module.purview_foreign):
            print(f"NOTE     {module.name}: 非本模块头 {spelling} 直接出现在 "
                  f".cppm 的 purview 中（prelude 已先行展开所以能编译；建议把该 "
                  f"include 移入全局片段）", file=sys.stderr)

    if drifted:
        print(f"\n{len(drifted)} 个 prelude 与 include 集不一致："
              f"{', '.join(drifted)}", file=sys.stderr)
        print("运行 scripts/gen_module_prelude.py 重新生成。", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
