// GENERATED by scripts/gen_module_prelude.py — 请勿手改，手改会被覆盖。
//
// 不变量：一切非本模块头（标准库/系统/第三方/其它 galay 模块）必须在全局
// 模块片段内展开；purview 只允许本模块头。本文件由工具从各 .cppm 的 include
// 集自动推导，条目为安全超集（__has_include 守卫，平台缺失自动跳过）。
// 增删 include 后请重新生成：
//
//     scripts/gen_module_prelude.py            # 全部模块
//     scripts/gen_module_prelude.py --check    # 门禁校验（漂移则失败）
//
// 依据：docs/plans/module-support.md「模块接口单元结构」。

#pragma once

#if __has_include("../../galay-http/builder/http_builder.h")
#include "../../galay-http/builder/http_builder.h"
#endif
#if __has_include("../../galay-http/common/http_log.h")
#include "../../galay-http/common/http_log.h"
#endif
#if __has_include("../../galay-http/common/iovec_utils.h")
#include "../../galay-http/common/iovec_utils.h"
#endif
#if __has_include("../../galay-http/common/macro.hpp")
#include "../../galay-http/common/macro.hpp"
#endif
#if __has_include("../../galay-http/kernel/http_conn.h")
#include "../../galay-http/kernel/http_conn.h"
#endif
#if __has_include("../../galay-http/kernel/http_reader.h")
#include "../../galay-http/kernel/http_reader.h"
#endif
#if __has_include("../../galay-http/kernel/http_writer.h")
#include "../../galay-http/kernel/http_writer.h"
#endif
#if __has_include("../../galay-http/kernel/reader_settings.h")
#include "../../galay-http/kernel/reader_settings.h"
#endif
#if __has_include("../../galay-http/kernel/writer_settings.h")
#include "../../galay-http/kernel/writer_settings.h"
#endif
#if __has_include("../../galay-http/protoc/http_base.h")
#include "../../galay-http/protoc/http_base.h"
#endif
#if __has_include("../../galay-http/protoc/http_body.h")
#include "../../galay-http/protoc/http_body.h"
#endif
#if __has_include("../../galay-http/protoc/http_chunk.h")
#include "../../galay-http/protoc/http_chunk.h"
#endif
#if __has_include("../../galay-http/protoc/http_error.h")
#include "../../galay-http/protoc/http_error.h"
#endif
#if __has_include("../../galay-http/protoc/http_header.h")
#include "../../galay-http/protoc/http_header.h"
#endif
#if __has_include("../../galay-http/protoc/http_request.h")
#include "../../galay-http/protoc/http_request.h"
#endif
#if __has_include("../../galay-http/protoc/http_request.inl")
#include "../../galay-http/protoc/http_request.inl"
#endif
#if __has_include("../../galay-http/protoc/http_response.h")
#include "../../galay-http/protoc/http_response.h"
#endif
#if __has_include("../../galay-http/protoc/http_response.inl")
#include "../../galay-http/protoc/http_response.inl"
#endif
#if __has_include("../../galay-http/protoc/parse_utils.h")
#include "../../galay-http/protoc/parse_utils.h"
#endif
#if __has_include("../../galay-http/protoc/route_params.h")
#include "../../galay-http/protoc/route_params.h"
#endif
#if __has_include("../../galay-kernel/async/async_tcp.h")
#include "../../galay-kernel/async/async_tcp.h"
#endif
#if __has_include("../../galay-kernel/common/concepts.h")
#include "../../galay-kernel/common/concepts.h"
#endif
#if __has_include("../../galay-kernel/common/defn.hpp")
#include "../../galay-kernel/common/defn.hpp"
#endif
#if __has_include("../../galay-kernel/common/error.h")
#include "../../galay-kernel/common/error.h"
#endif
#if __has_include("../../galay-kernel/common/handle_option.h")
#include "../../galay-kernel/common/handle_option.h"
#endif
#if __has_include("../../galay-kernel/common/host.hpp")
#include "../../galay-kernel/common/host.hpp"
#endif
#if __has_include("../../galay-kernel/common/kernel_config.h")
#include "../../galay-kernel/common/kernel_config.h"
#endif
#if __has_include("../../galay-kernel/common/log_macro.h")
#include "../../galay-kernel/common/log_macro.h"
#endif
#if __has_include("../../galay-kernel/common/logger.h")
#include "../../galay-kernel/common/logger.h"
#endif
#if __has_include("../../galay-kernel/common/timer.hpp")
#include "../../galay-kernel/common/timer.hpp"
#endif
#if __has_include("../../galay-kernel/common/timer_manager.hpp")
#include "../../galay-kernel/common/timer_manager.hpp"
#endif
#if __has_include("../../galay-kernel/core/awaitable.h")
#include "../../galay-kernel/core/awaitable.h"
#endif
#if __has_include("../../galay-kernel/core/awaitable.inl")
#include "../../galay-kernel/core/awaitable.inl"
#endif
#if __has_include("../../galay-kernel/core/io_controller.hpp")
#include "../../galay-kernel/core/io_controller.hpp"
#endif
#if __has_include("../../galay-kernel/core/io_handlers.hpp")
#include "../../galay-kernel/core/io_handlers.hpp"
#endif
#if __has_include("../../galay-kernel/core/io_scheduler.hpp")
#include "../../galay-kernel/core/io_scheduler.hpp"
#endif
#if __has_include("../../galay-kernel/core/scheduler.hpp")
#include "../../galay-kernel/core/scheduler.hpp"
#endif
#if __has_include("../../galay-kernel/core/task.h")
#include "../../galay-kernel/core/task.h"
#endif
#if __has_include("../../galay-kernel/core/timeout.hpp")
#include "../../galay-kernel/core/timeout.hpp"
#endif
#if __has_include("../../galay-kernel/core/waker.h")
#include "../../galay-kernel/core/waker.h"
#endif
#if __has_include("../../galay-kernel/core/watch_defs.hpp")
#include "../../galay-kernel/core/watch_defs.hpp"
#endif
#if __has_include("../../galay-ssl/async/awaitable.h")
#include "../../galay-ssl/async/awaitable.h"
#endif
#if __has_include("../../galay-ssl/async/ssl_await.h")
#include "../../galay-ssl/async/ssl_await.h"
#endif
#if __has_include("../../galay-ssl/async/ssl_socket.h")
#include "../../galay-ssl/async/ssl_socket.h"
#endif
#if __has_include("../../galay-ssl/common/defn.hpp")
#include "../../galay-ssl/common/defn.hpp"
#endif
#if __has_include("../../galay-ssl/common/error.h")
#include "../../galay-ssl/common/error.h"
#endif
#if __has_include("../../galay-ssl/ssl/ssl_context.h")
#include "../../galay-ssl/ssl/ssl_context.h"
#endif
#if __has_include("../../galay-ssl/ssl/ssl_engine.h")
#include "../../galay-ssl/ssl/ssl_engine.h"
#endif
#if __has_include("../../galay-utils/cache/bytes.hpp")
#include "../../galay-utils/cache/bytes.hpp"
#endif
#if __has_include("../../galay-utils/cache/ring_buffer.hpp")
#include "../../galay-utils/cache/ring_buffer.hpp"
#endif
#if __has_include("../../galay-utils/common/defn.hpp")
#include "../../galay-utils/common/defn.hpp"
#endif
#if __has_include("../../galay-utils/common/macro.hpp")
#include "../../galay-utils/common/macro.hpp"
#endif
#if __has_include("../../galay-utils/encoding/base64.hpp")
#include "../../galay-utils/encoding/base64.hpp"
#endif
#if __has_include(<WinSock2.h>)
#include <WinSock2.h>
#endif
#if __has_include(<algorithm>)
#include <algorithm>
#endif
#if __has_include(<arpa/inet.h>)
#include <arpa/inet.h>
#endif
#if __has_include(<array>)
#include <array>
#endif
#if __has_include(<atomic>)
#include <atomic>
#endif
#if __has_include(<bit>)
#include <bit>
#endif
#if __has_include(<bitset>)
#include <bitset>
#endif
#if __has_include(<cctype>)
#include <cctype>
#endif
#if __has_include(<cerrno>)
#include <cerrno>
#endif
#if __has_include(<charconv>)
#include <charconv>
#endif
#if __has_include(<chrono>)
#include <chrono>
#endif
#if __has_include(<concepts>)
#include <concepts>
#endif
#if __has_include(<condition_variable>)
#include <condition_variable>
#endif
#if __has_include(<coroutine>)
#include <coroutine>
#endif
#if __has_include(<cstddef>)
#include <cstddef>
#endif
#if __has_include(<cstdint>)
#include <cstdint>
#endif
#if __has_include(<cstdio>)
#include <cstdio>
#endif
#if __has_include(<cstdlib>)
#include <cstdlib>
#endif
#if __has_include(<cstring>)
#include <cstring>
#endif
#if __has_include(<ctime>)
#include <ctime>
#endif
#if __has_include(<deque>)
#include <deque>
#endif
#if __has_include(<exception>)
#include <exception>
#endif
#if __has_include(<expected>)
#include <expected>
#endif
#if __has_include(<fcntl.h>)
#include <fcntl.h>
#endif
#if __has_include(<format>)
#include <format>
#endif
#if __has_include(<functional>)
#include <functional>
#endif
#if __has_include(<galay/thirdparty/concurrentqueue/moodycamel/concurrentqueue.h>)
#include <galay/thirdparty/concurrentqueue/moodycamel/concurrentqueue.h>
#endif
// <libaio.h> 的 io_* 帮助函数是 static inline：在 purview 内展开同样触发 "exporting declaration ... with internal linkage"。
#if __has_include(<libaio.h>)
#include <libaio.h>
#endif
// liburing 通过 Linux 头文件暴露通用的 BLOCK_SIZE 宏；清理该宏以免与 vendored concurrentqueue 的同名类成员冲突。
#if __has_include(<liburing.h>)
#include <liburing.h>
#endif
#ifdef BLOCK_SIZE
#undef BLOCK_SIZE
#endif
#if __has_include(<limits>)
#include <limits>
#endif
#if __has_include(<linux/time_types.h>)
#include <linux/time_types.h>
#endif
#if __has_include(<list>)
#include <list>
#endif
#if __has_include(<map>)
#include <map>
#endif
#if __has_include(<memory>)
#include <memory>
#endif
#if __has_include(<mutex>)
#include <mutex>
#endif
#if __has_include(<netinet/in.h>)
#include <netinet/in.h>
#endif
#if __has_include(<new>)
#include <new>
#endif
#if __has_include(<openssl/err.h>)
#include <openssl/err.h>
#endif
#if __has_include(<openssl/ssl.h>)
#include <openssl/ssl.h>
#endif
#if __has_include(<openssl/x509.h>)
#include <openssl/x509.h>
#endif
#if __has_include(<optional>)
#include <optional>
#endif
#if __has_include(<random>)
#include <random>
#endif
#if __has_include(<span>)
#include <span>
#endif
#if __has_include(<string>)
#include <string>
#endif
#if __has_include(<string_view>)
#include <string_view>
#endif
#if __has_include(<sys/epoll.h>)
#include <sys/epoll.h>
#endif
#if __has_include(<sys/event.h>)
#include <sys/event.h>
#endif
#if __has_include(<sys/inotify.h>)
#include <sys/inotify.h>
#endif
#if __has_include(<sys/mman.h>)
#include <sys/mman.h>
#endif
#if __has_include(<sys/sendfile.h>)
#include <sys/sendfile.h>
#endif
#if __has_include(<sys/socket.h>)
#include <sys/socket.h>
#endif
#if __has_include(<sys/stat.h>)
#include <sys/stat.h>
#endif
#if __has_include(<sys/syscall.h>)
#include <sys/syscall.h>
#endif
#if __has_include(<sys/types.h>)
#include <sys/types.h>
#endif
#if __has_include(<sys/uio.h>)
#include <sys/uio.h>
#endif
#if __has_include(<system_error>)
#include <system_error>
#endif
#if __has_include(<thread>)
#include <thread>
#endif
#if __has_include(<type_traits>)
#include <type_traits>
#endif
#if __has_include(<unistd.h>)
#include <unistd.h>
#endif
#if __has_include(<unordered_map>)
#include <unordered_map>
#endif
#if __has_include(<utility>)
#include <utility>
#endif
#if __has_include(<variant>)
#include <variant>
#endif
#if __has_include(<vector>)
#include <vector>
#endif
