ServerRoot "/usr"
Listen 127.0.0.1:18082
PidFile "/Users/gongzhijie/Desktop/projects/git/galay/docs/cpp/modules/http/configs/httpd-runtime/httpd.pid"
ErrorLog "/Users/gongzhijie/Desktop/projects/git/galay/docs/cpp/modules/http/configs/httpd-runtime/error.log"
CustomLog "/Users/gongzhijie/Desktop/projects/git/galay/docs/cpp/modules/http/configs/httpd-runtime/access.log" common
LogLevel warn
ServerName 127.0.0.1

LoadModule mpm_prefork_module libexec/apache2/mod_mpm_prefork.so
LoadModule authz_core_module libexec/apache2/mod_authz_core.so
LoadModule authz_host_module libexec/apache2/mod_authz_host.so
LoadModule mime_module libexec/apache2/mod_mime.so
LoadModule log_config_module libexec/apache2/mod_log_config.so
LoadModule unixd_module libexec/apache2/mod_unixd.so
LoadModule dir_module libexec/apache2/mod_dir.so

User _www
Group _www
TypesConfig "/private/etc/apache2/mime.types"
DocumentRoot "/Users/gongzhijie/Desktop/projects/git/galay/docs/cpp/modules/http/configs/www"
DirectoryIndex index.html
KeepAlive On
MaxKeepAliveRequests 100000
KeepAliveTimeout 60
Timeout 5

<IfModule mpm_prefork_module>
    StartServers 4
    MinSpareServers 4
    MaxSpareServers 8
    MaxRequestWorkers 100
    MaxConnectionsPerChild 0
</IfModule>

<Directory "/Users/gongzhijie/Desktop/projects/git/galay/docs/cpp/modules/http/configs/www">
    Require all granted
    Options -Indexes
    AllowOverride None
</Directory>
