include_guard(GLOBAL)

option(GALAY_BUILD_UTILS "Build the utils module" ON)
option(GALAY_BUILD_KERNEL "Build the kernel module" ON)
option(GALAY_BUILD_SSL "Build the ssl module" OFF)
option(GALAY_BUILD_HTTP "Build the http module" OFF)
option(GALAY_BUILD_WS "Build the websocket module" OFF)
option(GALAY_BUILD_HTTP2 "Build the http2 module" OFF)
option(GALAY_BUILD_REDIS "Build the redis module" OFF)
option(GALAY_BUILD_ETCD "Build the etcd module" OFF)
option(GALAY_BUILD_MONGO "Build the mongo module" OFF)
option(GALAY_BUILD_MYSQL "Build the mysql module" OFF)
option(GALAY_BUILD_RPC "Build the rpc module" OFF)
option(GALAY_BUILD_MCP "Build the mcp module" OFF)
option(GALAY_BUILD_TRACING "Build the tracing module" OFF)

option(GALAY_BUILD_EXAMPLES "Build enabled module examples" OFF)
option(GALAY_BUILD_BENCHMARKS "Build enabled module benchmarks" OFF)
option(GALAY_ENABLE_CPP23_MODULES "Build enabled module C++23 facade targets when supported" OFF)
option(GALAY_BUILD_SHARED_LIBS "Build non-header modules as shared libraries" ON)
option(GALAY_DISABLE_IOURING "Disable io_uring and use epoll on Linux" ON)

option(GALAY_TRACING_ENABLE_SPDLOG "Enable the tracing spdlog adapter" OFF)
option(GALAY_TRACING_ENABLE_KERNEL "Enable the tracing kernel adapter" OFF)
option(GALAY_TRACING_ENABLE_OTLP_HTTP "Enable the tracing OTLP/HTTP exporter" OFF)

set(BUILD_SHARED_LIBS "${GALAY_BUILD_SHARED_LIBS}" CACHE BOOL "Build shared libraries" FORCE)
set(ENABLE_CPP23_MODULES "${GALAY_ENABLE_CPP23_MODULES}" CACHE BOOL "Enable C++23 module targets" FORCE)

if(GALAY_BUILD_KERNEL AND NOT GALAY_BUILD_UTILS)
    message(FATAL_ERROR "GALAY_BUILD_KERNEL requires GALAY_BUILD_UTILS")
endif()
if(GALAY_BUILD_SSL AND NOT GALAY_BUILD_KERNEL)
    message(FATAL_ERROR "GALAY_BUILD_SSL requires GALAY_BUILD_KERNEL")
endif()
if(GALAY_BUILD_HTTP AND NOT GALAY_BUILD_KERNEL)
    message(FATAL_ERROR "GALAY_BUILD_HTTP requires GALAY_BUILD_KERNEL")
endif()
if(GALAY_BUILD_WS AND NOT GALAY_BUILD_HTTP)
    message(FATAL_ERROR "GALAY_BUILD_WS requires GALAY_BUILD_HTTP")
endif()
if(GALAY_BUILD_HTTP2 AND NOT GALAY_BUILD_HTTP)
    message(FATAL_ERROR "GALAY_BUILD_HTTP2 requires GALAY_BUILD_HTTP")
endif()

if(GALAY_BUILD_SSL)
    set(GALAY_SSL_FEATURE_ENABLED ON)
else()
    set(GALAY_SSL_FEATURE_ENABLED OFF)
endif()
