include_guard(GLOBAL)

option(GALAY_BUILD_UTILS "Build the utils module" ON)
option(GALAY_BUILD_KERNEL "Build the kernel module" ON)
option(GALAY_BUILD_SSL "Build the ssl module" ON)
option(GALAY_BUILD_HTTP "Build the http module" ON)
option(GALAY_BUILD_WS "Build the websocket module" ON)
option(GALAY_BUILD_HTTP2 "Build the http2 module" ON)
option(GALAY_BUILD_REDIS "Build the redis module" ON)
option(GALAY_BUILD_ETCD "Build the etcd module" ON)
option(GALAY_BUILD_MONGO "Build the mongo module" ON)
option(GALAY_BUILD_MYSQL "Build the mysql module" ON)
option(GALAY_BUILD_RPC "Build the rpc module" ON)
option(GALAY_BUILD_MCP "Build the mcp module" ON)
option(GALAY_BUILD_TRACING "Build the tracing module" ON)

option(BUILD_TESTING "Build tests" ON)
option(GALAY_BUILD_EXAMPLES "Build enabled module examples" ON)
option(GALAY_BUILD_BENCHMARKS "Build enabled module benchmarks" ON)
option(GALAY_BUILD_C_API "Build C ABI wrapper targets" OFF)
option(GALAY_ENABLE_CPP23_MODULES "Build enabled module C++23 facade targets when supported" OFF)
option(GALAY_BUILD_SHARED_LIBS "Build non-header modules as shared libraries" ON)
option(GALAY_DISABLE_IOURING "Disable io_uring and use epoll on Linux" ON)

option(GALAY_TRACING_ENABLE_SPDLOG "Enable the tracing spdlog adapter" OFF)
option(GALAY_TRACING_ENABLE_GALAY_HTTP_OTLP_TRANSPORT "Enable the built-in galay-http OTLP transport" OFF)
option(GALAY_RPC_ENABLE_ETCD "Compile the RPC etcd discovery adapter into galay::rpc" OFF)

if(DEFINED GALAY_TRACING_ENABLE_OTLP_HTTP)
    message(DEPRECATION
        "GALAY_TRACING_ENABLE_OTLP_HTTP is deprecated; use "
        "GALAY_TRACING_ENABLE_GALAY_HTTP_OTLP_TRANSPORT.")
    set(GALAY_TRACING_ENABLE_GALAY_HTTP_OTLP_TRANSPORT
        "${GALAY_TRACING_ENABLE_OTLP_HTTP}"
        CACHE BOOL "Enable the built-in galay-http OTLP transport" FORCE)
endif()

set(BUILD_SHARED_LIBS "${GALAY_BUILD_SHARED_LIBS}" CACHE BOOL "Build shared libraries" FORCE)
set(ENABLE_CPP23_MODULES "${GALAY_ENABLE_CPP23_MODULES}" CACHE BOOL "Enable C++23 module targets" FORCE)

if(GALAY_BUILD_KERNEL AND NOT GALAY_BUILD_UTILS)
    message(FATAL_ERROR "GALAY_BUILD_KERNEL requires GALAY_BUILD_UTILS")
endif()
if(GALAY_BUILD_SSL AND NOT GALAY_BUILD_KERNEL)
    message(FATAL_ERROR "GALAY_BUILD_SSL requires GALAY_BUILD_KERNEL")
endif()
if(GALAY_BUILD_HTTP AND NOT GALAY_BUILD_KERNEL)
    message(FATAL_ERROR "GALAY_BUILD_HTTP requires GALAY_BUILD_KERNEL")
endif()
if(GALAY_BUILD_WS AND NOT GALAY_BUILD_HTTP)
    message(FATAL_ERROR "GALAY_BUILD_WS requires GALAY_BUILD_HTTP")
endif()
if(GALAY_BUILD_HTTP2 AND NOT GALAY_BUILD_HTTP)
    message(FATAL_ERROR "GALAY_BUILD_HTTP2 requires GALAY_BUILD_HTTP")
endif()
if(GALAY_RPC_ENABLE_ETCD AND NOT GALAY_BUILD_RPC)
    message(FATAL_ERROR "GALAY_RPC_ENABLE_ETCD requires GALAY_BUILD_RPC")
endif()
if(GALAY_RPC_ENABLE_ETCD AND NOT GALAY_BUILD_ETCD)
    message(FATAL_ERROR "GALAY_RPC_ENABLE_ETCD requires GALAY_BUILD_ETCD")
endif()

if(GALAY_BUILD_SSL)
    set(GALAY_SSL_FEATURE_ENABLED ON)
else()
    set(GALAY_SSL_FEATURE_ENABLED OFF)
endif()
